{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "472eedd8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import PIL\n",
    "import matplotlib.patches as patches\n",
    "import matplotlib.pyplot as plt\n",
    "import tensorflow as tf\n",
    "from sklearn.model_selection import train_test_split\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D\n",
    "from tensorflow.keras.preprocessing import image"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "610903cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['image_id', '5_o_Clock_Shadow', 'Arched_Eyebrows', 'Attractive',\n",
      "       'Bags_Under_Eyes', 'Bald', 'Bangs', 'Big_Lips', 'Big_Nose',\n",
      "       'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows',\n",
      "       'Chubby', 'Double_Chin', 'Eyeglasses', 'Goatee', 'Gray_Hair',\n",
      "       'Heavy_Makeup', 'High_Cheekbones', 'Male', 'Mouth_Slightly_Open',\n",
      "       'Mustache', 'Narrow_Eyes', 'No_Beard', 'Oval_Face', 'Pale_Skin',\n",
      "       'Pointy_Nose', 'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns',\n",
      "       'Smiling', 'Straight_Hair', 'Wavy_Hair', 'Wearing_Earrings',\n",
      "       'Wearing_Hat', 'Wearing_Lipstick', 'Wearing_Necklace',\n",
      "       'Wearing_Necktie', 'Young'],\n",
      "      dtype='object')\n",
      "Samples Training Set: 6999\n",
      "Samples in Validation Data: 1500\n",
      "Samples in Test Data: 1500\n",
      "Batch size: 8\n",
      "Epoch 1/10\n",
      "875/875 [==============================] - 54s 58ms/step - loss: 0.5192 - precision: 0.5104 - recall: 0.3696 - binary_accuracy: 0.8511 - val_loss: 0.4242 - val_precision: 0.4402 - val_recall: 0.8405 - val_binary_accuracy: 0.8100\n",
      "Epoch 2/10\n",
      "875/875 [==============================] - 52s 60ms/step - loss: 0.2895 - precision: 0.6634 - recall: 0.4471 - binary_accuracy: 0.8821 - val_loss: 0.2723 - val_precision: 0.6544 - val_recall: 0.6121 - val_binary_accuracy: 0.8900\n",
      "Epoch 3/10\n",
      "875/875 [==============================] - 53s 61ms/step - loss: 0.2699 - precision: 0.6826 - recall: 0.4594 - binary_accuracy: 0.8860 - val_loss: 0.2863 - val_precision: 0.7021 - val_recall: 0.2845 - val_binary_accuracy: 0.8707\n",
      "Epoch 4/10\n",
      "875/875 [==============================] - 54s 61ms/step - loss: 0.2646 - precision: 0.6969 - recall: 0.4716 - binary_accuracy: 0.8891 - val_loss: 0.3070 - val_precision: 0.5647 - val_recall: 0.8276 - val_binary_accuracy: 0.8747\n",
      "Epoch 5/10\n",
      "875/875 [==============================] - 54s 62ms/step - loss: 0.2568 - precision: 0.7061 - recall: 0.4792 - binary_accuracy: 0.8911 - val_loss: 0.3464 - val_precision: 0.2500 - val_recall: 0.0043 - val_binary_accuracy: 0.8440\n",
      "Epoch 6/10\n",
      "875/875 [==============================] - 54s 62ms/step - loss: 0.2558 - precision: 0.7024 - recall: 0.4773 - binary_accuracy: 0.8904 - val_loss: 0.2633 - val_precision: 0.8182 - val_recall: 0.3103 - val_binary_accuracy: 0.8827\n",
      "Epoch 7/10\n",
      "875/875 [==============================] - 55s 63ms/step - loss: 0.2490 - precision: 0.6940 - recall: 0.5123 - binary_accuracy: 0.8921 - val_loss: 0.3348 - val_precision: 0.6316 - val_recall: 0.1034 - val_binary_accuracy: 0.8520\n",
      "Epoch 8/10\n",
      "875/875 [==============================] - 55s 63ms/step - loss: 0.2517 - precision: 0.7158 - recall: 0.5000 - binary_accuracy: 0.8944 - val_loss: 0.2765 - val_precision: 0.6503 - val_recall: 0.5129 - val_binary_accuracy: 0.8820\n",
      "Epoch 9/10\n",
      "875/875 [==============================] - 55s 62ms/step - loss: 0.2440 - precision: 0.7197 - recall: 0.5170 - binary_accuracy: 0.8966 - val_loss: 0.2655 - val_precision: 0.8023 - val_recall: 0.2974 - val_binary_accuracy: 0.8800\n",
      "Epoch 10/10\n",
      "875/875 [==============================] - 55s 62ms/step - loss: 0.2384 - precision: 0.7576 - recall: 0.5406 - binary_accuracy: 0.9044 - val_loss: 0.2481 - val_precision: 0.6900 - val_recall: 0.6810 - val_binary_accuracy: 0.9033\n",
      "INFO:tensorflow:Assets written to: cnn85_checkpoints/iter1\\assets\n",
      "Model 1evaluating:\n",
      "47/47 [==============================] - 2s 49ms/step - loss: 0.2481 - precision: 0.6900 - recall: 0.6810 - binary_accuracy: 0.9033\n",
      "model loaded: iter1\n",
      "training model 2\n",
      "Samples Training Set: 6999\n",
      "Samples in Validation Data: 1500\n",
      "Samples in Test Data: 1500\n",
      "Batch size: 8\n",
      "Epoch 1/10\n",
      "875/875 [==============================] - 47s 51ms/step - loss: 0.2471 - precision: 0.7025 - recall: 0.4864 - binary_accuracy: 0.8977 - val_loss: 0.2673 - val_precision: 0.5857 - val_recall: 0.7387 - val_binary_accuracy: 0.8960\n",
      "Epoch 2/10\n",
      "875/875 [==============================] - 44s 51ms/step - loss: 0.2354 - precision: 0.7141 - recall: 0.5045 - binary_accuracy: 0.9008 - val_loss: 0.2190 - val_precision: 0.6391 - val_recall: 0.7387 - val_binary_accuracy: 0.9100\n",
      "Epoch 3/10\n",
      "875/875 [==============================] - 48s 55ms/step - loss: 0.2268 - precision: 0.7528 - recall: 0.5357 - binary_accuracy: 0.9090 - val_loss: 0.2103 - val_precision: 0.7143 - val_recall: 0.6030 - val_binary_accuracy: 0.9153\n",
      "Epoch 4/10\n",
      "875/875 [==============================] - 115s 131ms/step - loss: 0.2284 - precision: 0.7277 - recall: 0.5236 - binary_accuracy: 0.9044 - val_loss: 0.1967 - val_precision: 0.6860 - val_recall: 0.5930 - val_binary_accuracy: 0.9100\n",
      "Epoch 5/10\n",
      "875/875 [==============================] - 113s 129ms/step - loss: 0.2135 - precision: 0.7641 - recall: 0.5859 - binary_accuracy: 0.9154 - val_loss: 0.2085 - val_precision: 0.6836 - val_recall: 0.6080 - val_binary_accuracy: 0.9107\n",
      "Epoch 6/10\n",
      "875/875 [==============================] - 120s 137ms/step - loss: 0.2105 - precision: 0.7737 - recall: 0.5910 - binary_accuracy: 0.9173 - val_loss: 0.2311 - val_precision: 0.6406 - val_recall: 0.6985 - val_binary_accuracy: 0.9080\n",
      "Epoch 7/10\n",
      "875/875 [==============================] - 120s 137ms/step - loss: 0.2050 - precision: 0.7864 - recall: 0.6030 - binary_accuracy: 0.9203 - val_loss: 0.2712 - val_precision: 0.5390 - val_recall: 0.8342 - val_binary_accuracy: 0.8833\n",
      "Epoch 8/10\n",
      "875/875 [==============================] - 119s 137ms/step - loss: 0.2044 - precision: 0.7756 - recall: 0.6080 - binary_accuracy: 0.9193 - val_loss: 0.1875 - val_precision: 0.7485 - val_recall: 0.6131 - val_binary_accuracy: 0.9213\n",
      "Epoch 9/10\n",
      "875/875 [==============================] - 118s 135ms/step - loss: 0.1974 - precision: 0.7859 - recall: 0.6382 - binary_accuracy: 0.9238 - val_loss: 0.2278 - val_precision: 0.5709 - val_recall: 0.7889 - val_binary_accuracy: 0.8933\n",
      "Epoch 10/10\n",
      "875/875 [==============================] - 120s 137ms/step - loss: 0.1912 - precision: 0.7802 - recall: 0.6352 - binary_accuracy: 0.9227 - val_loss: 0.1824 - val_precision: 0.7320 - val_recall: 0.7136 - val_binary_accuracy: 0.9273\n",
      "INFO:tensorflow:Assets written to: cnn85_checkpoints/iter2\\assets\n",
      "Model 2evaluating:\n",
      "47/47 [==============================] - 9s 193ms/step - loss: 0.1824 - precision: 0.7320 - recall: 0.7136 - binary_accuracy: 0.9273\n",
      "model loaded: iter2\n",
      "training model 3\n",
      "Samples Training Set: 6999\n",
      "Samples in Validation Data: 1500\n",
      "Samples in Test Data: 1500\n",
      "Batch size: 8\n",
      "SGD\n",
      "Epoch 1/10\n",
      "  4/875 [..............................] - ETA: 1:30 - loss: 4169875836633088.0000 - precision: 0.0000e+00 - recall: 0.0000e+00 - binary_accuracy: 0.6875"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'assert_greater_equal/Assert/AssertGuard/Assert' defined at (most recent call last):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n      app.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\foreh\\AppData\\Local\\Temp/ipykernel_9408/1572046965.py\", line 109, in <module>\n      training_process = model.fit(X_train,y_train,epochs = 10,validation_data = (X_val,y_val),batch_size=BATCH_SIZE,shuffle = True)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 864, in train_step\n      return self.compute_metrics(x, y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 957, in compute_metrics\n      self.compiled_metrics.update_state(y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 459, in update_state\n      metric_obj.update_state(y_t, y_p, sample_weight=mask)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 70, in decorated\n      update_op = update_state_fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 178, in update_state_fn\n      return ag_update_state(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 1403, in update_state\n      return metrics_utils.update_confusion_matrix_variables(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 602, in update_confusion_matrix_variables\n      tf.compat.v1.assert_greater_equal(\nNode: 'assert_greater_equal/Assert/AssertGuard/Assert'\nDetected at node 'assert_greater_equal/Assert/AssertGuard/Assert' defined at (most recent call last):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n      app.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\foreh\\AppData\\Local\\Temp/ipykernel_9408/1572046965.py\", line 109, in <module>\n      training_process = model.fit(X_train,y_train,epochs = 10,validation_data = (X_val,y_val),batch_size=BATCH_SIZE,shuffle = True)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 864, in train_step\n      return self.compute_metrics(x, y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 957, in compute_metrics\n      self.compiled_metrics.update_state(y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 459, in update_state\n      metric_obj.update_state(y_t, y_p, sample_weight=mask)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 70, in decorated\n      update_op = update_state_fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 178, in update_state_fn\n      return ag_update_state(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 1403, in update_state\n      return metrics_utils.update_confusion_matrix_variables(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 602, in update_confusion_matrix_variables\n      tf.compat.v1.assert_greater_equal(\nNode: 'assert_greater_equal/Assert/AssertGuard/Assert'\n2 root error(s) found.\n  (0) INVALID_ARGUMENT:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential/dense_4/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]\n\t [[{{node assert_greater_equal/Assert/AssertGuard/Assert}}]]\n\t [[assert_less_equal_1/Assert/AssertGuard/pivot_f/_33/_83]]\n  (1) INVALID_ARGUMENT:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential/dense_4/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]\n\t [[{{node assert_greater_equal/Assert/AssertGuard/Assert}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_train_function_305000]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_9408/1572046965.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m    107\u001b[0m           \u001b[0mopt\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mkeras\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0moptimizers\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mAdam\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlearning_rate\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m0.003\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    108\u001b[0m           \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcompile\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0moptimizer\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mopt\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mloss\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"binary_crossentropy\"\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mmetrics\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mkeras\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmetrics\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mPrecision\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mkeras\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmetrics\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mRecall\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'binary_accuracy'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 109\u001b[1;33m     \u001b[0mtraining_process\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0my_train\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mepochs\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m10\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mvalidation_data\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mX_val\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0my_val\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mbatch_size\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mBATCH_SIZE\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mshuffle\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    110\u001b[0m     \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msave\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'cnn85_checkpoints/iter'\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mi\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    111\u001b[0m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Model \"\u001b[0m \u001b[1;33m+\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mi\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m+\u001b[0m\u001b[1;34m\"evaluating:\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     65\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m  \u001b[1;31m# pylint: disable=broad-except\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 67\u001b[1;33m       \u001b[1;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     68\u001b[0m     \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     69\u001b[0m       \u001b[1;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     52\u001b[0m   \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     53\u001b[0m     \u001b[0mctx\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 54\u001b[1;33m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[0;32m     55\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[0;32m     56\u001b[0m   \u001b[1;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'assert_greater_equal/Assert/AssertGuard/Assert' defined at (most recent call last):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n      app.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\foreh\\AppData\\Local\\Temp/ipykernel_9408/1572046965.py\", line 109, in <module>\n      training_process = model.fit(X_train,y_train,epochs = 10,validation_data = (X_val,y_val),batch_size=BATCH_SIZE,shuffle = True)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 864, in train_step\n      return self.compute_metrics(x, y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 957, in compute_metrics\n      self.compiled_metrics.update_state(y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 459, in update_state\n      metric_obj.update_state(y_t, y_p, sample_weight=mask)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 70, in decorated\n      update_op = update_state_fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 178, in update_state_fn\n      return ag_update_state(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 1403, in update_state\n      return metrics_utils.update_confusion_matrix_variables(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 602, in update_confusion_matrix_variables\n      tf.compat.v1.assert_greater_equal(\nNode: 'assert_greater_equal/Assert/AssertGuard/Assert'\nDetected at node 'assert_greater_equal/Assert/AssertGuard/Assert' defined at (most recent call last):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n      app.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\foreh\\AppData\\Local\\Temp/ipykernel_9408/1572046965.py\", line 109, in <module>\n      training_process = model.fit(X_train,y_train,epochs = 10,validation_data = (X_val,y_val),batch_size=BATCH_SIZE,shuffle = True)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 864, in train_step\n      return self.compute_metrics(x, y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py\", line 957, in compute_metrics\n      self.compiled_metrics.update_state(y, y_pred, sample_weight)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 459, in update_state\n      metric_obj.update_state(y_t, y_p, sample_weight=mask)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 70, in decorated\n      update_op = update_state_fn(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 178, in update_state_fn\n      return ag_update_state(*args, **kwargs)\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\metrics.py\", line 1403, in update_state\n      return metrics_utils.update_confusion_matrix_variables(\n    File \"C:\\Users\\foreh\\anaconda3\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 602, in update_confusion_matrix_variables\n      tf.compat.v1.assert_greater_equal(\nNode: 'assert_greater_equal/Assert/AssertGuard/Assert'\n2 root error(s) found.\n  (0) INVALID_ARGUMENT:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential/dense_4/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]\n\t [[{{node assert_greater_equal/Assert/AssertGuard/Assert}}]]\n\t [[assert_less_equal_1/Assert/AssertGuard/pivot_f/_33/_83]]\n  (1) INVALID_ARGUMENT:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential/dense_4/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]\n\t [[{{node assert_greater_equal/Assert/AssertGuard/Assert}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_train_function_305000]"
     ]
    }
   ],
   "source": [
    "attr_data_path = \"list_attr_celeba.csv\"\n",
    "images_data_path = \"C:/Users/foreh/Documents/celebaRepo/FacialAttrCNN/celeba/archive/img_align_celeba/img_align_celeba\"\n",
    "images_data_size = 10000 \n",
    "\n",
    "tf.keras.backend.clear_session()\n",
    "width = 178\n",
    "height = 218\n",
    "x_ = 100                            # new value of x\n",
    "image_size_ratio = width / height    # dimensions ratio\n",
    "y_ = int(image_size_ratio * x_)  \n",
    "model = Sequential()\n",
    "model.add(tf.keras.Input(shape=(height, width,3)))\n",
    "model.add(tf.keras.layers.Normalization())\n",
    "\n",
    "model.add(Conv2D(filters=32,kernel_size=(3,3),padding = 'same'))\n",
    "model.add(Conv2D(filters=8, kernel_size=(3,3), padding='same'))\n",
    "model.add(tf.keras.layers.Normalization())\n",
    "\n",
    "model.add(Conv2D(filters=4, kernel_size=(3, 3), padding='same'))\n",
    "model.add(MaxPooling2D(pool_size=2))\n",
    "\n",
    "model.add(Dropout(0.2))\n",
    "\n",
    "model.add(Conv2D(filters=16,kernel_size=(3,3),padding = 'same'))\n",
    "model.add(Conv2D(filters=8,kernel_size=(2,2),padding = 'same'))\n",
    "model.add(tf.keras.layers.Normalization())\n",
    "\n",
    "model.add(Conv2D(filters=4, kernel_size=(3, 3), padding='same'))\n",
    "model.add(MaxPooling2D(pool_size=2))\n",
    "\n",
    "model.add(Dropout(0.2))\n",
    "\n",
    "model.add(Conv2D(filters=16,kernel_size=(3,3),padding = 'same'))\n",
    "model.add(Conv2D(filters=8,kernel_size=(2,2),padding = 'same'))\n",
    "## changed from (3,3)->(1,3)\n",
    "model.add(tf.keras.layers.Normalization())\n",
    "\n",
    "model.add(Conv2D(filters=4, kernel_size=(3, 3), padding='same'))\n",
    "model.add(MaxPooling2D(pool_size=4))\n",
    "\n",
    "model.add(Conv2D(filters=16, kernel_size=(3,3)))\n",
    "model.add(Conv2D(filters=16, kernel_size=(2,2)))\n",
    "model.add(tf.keras.layers.AveragePooling2D(pool_size=2))\n",
    "\n",
    "model.add(tf.keras.layers.Normalization())\n",
    "\n",
    "model.add(Flatten())\n",
    "model.add(Dense(64))\n",
    "model.add(Dense(32))\n",
    "model.add(Dense(48))\n",
    "model.add(Dense(16))\n",
    "model.add(Dense(1, activation='sigmoid'))\n",
    "original_image_size = (width,height)\n",
    "df_org = pd.read_csv(attr_data_path)\n",
    "print(df_org.columns)\n",
    "for i in range(1, 100):\n",
    "    if (i > 1):\n",
    "        model = tf.keras.models.load_model('cnn85_checkpoints/iter'+str(i-1))\n",
    "        print(\"model loaded: iter\"+str(i-1))\n",
    "        print(\"training model \"+str(i))\n",
    "    df = pd.DataFrame()\n",
    "    if((i+1) % 20 == 0):\n",
    "        df = df_org[(1+images_data_size*(i%20)):202600]\n",
    "    else:\n",
    "        df = df_org[(1+images_data_size*(i%20)):images_data_size*((i+1)%20)]\n",
    "    df = df.replace(-1,0)\n",
    "    #print(df.head(5))\n",
    "    images_data = list()\n",
    "    for idx in range(df.shape[0]):\n",
    "        path = \"{}/{}\".format(str(images_data_path),str(df.iloc[idx].image_id))\n",
    "        image = PIL.Image.open(path)\n",
    "        image_array = np.asarray(image)\n",
    "        images_data.append(image_array)\n",
    "    images_data = np.array(images_data)\n",
    "    def image_from_index(index, size=(original_image_size), path=images_data_path):\n",
    "        path = \"{}/{}\".format(str(path),str(df.iloc[index].image_id))\n",
    "        # to read the image\n",
    "        image = PIL.Image.open(path).resize(size)\n",
    "        image_array = np.asarray(image)\n",
    "\n",
    "        return image_array\n",
    "    images = images_data # list of array of images\n",
    "    labels = df[[\"image_id\", \"Blond_Hair\"]]  # dataframe of image features\n",
    "    train_images,test_images,train_labels,test_labels = train_test_split(images,labels,test_size=0.3,random_state=(i%6))\n",
    "    y_test=test_labels.drop([\"image_id\"],axis=1)\n",
    "    y_train=train_labels.drop([\"image_id\"],axis=1)\n",
    "\n",
    "    X_test=test_images\n",
    "    X_train=train_images\n",
    "    #X_train = tf.expand_dims(X_train, axis=-1)\n",
    "    print(\"Samples Training Set:\",len(X_train))\n",
    "    X_test, X_val, y_test, y_val=train_test_split(X_test, y_test,test_size=0.5,random_state=(i%5))\n",
    "    print(\"Samples in Validation Data:\",len(X_val))\n",
    "    print(\"Samples in Test Data:\",len(X_test))\n",
    "    x_ = original_image_size[0]\n",
    "    y_ = original_image_size[1]\n",
    "    BATCH_SIZE = (8)\n",
    "    print(\"Batch size: \" + str(BATCH_SIZE))\n",
    "    if i%3 == 1 or i%3 == 2:\n",
    "          model.compile(optimizer = \"nadam\",loss=\"binary_crossentropy\",metrics = [tf.keras.metrics.Precision(), tf.keras.metrics.Recall(), 'binary_accuracy'])\n",
    "    elif i%3 == 2 or i%3 == 0:\n",
    "          print(\"SGD\")\n",
    "          opt = tf.keras.optimizers.SGD(learning_rate=0.3)\n",
    "          model.compile(optimizer = opt,loss=\"binary_crossentropy\",metrics = [tf.keras.metrics.Precision(), tf.keras.metrics.Recall(), 'binary_accuracy'])\n",
    "    else:\n",
    "          print(\"ADAM\")\n",
    "          opt = tf.keras.optimizers.Adam(learning_rate=0.003)\n",
    "          model.compile(optimizer = opt,loss=\"binary_crossentropy\",metrics = [tf.keras.metrics.Precision(), tf.keras.metrics.Recall(), 'binary_accuracy'])\n",
    "    training_process = model.fit(X_train,y_train,epochs = 10,validation_data = (X_val,y_val),batch_size=BATCH_SIZE,shuffle = True)\n",
    "    model.save('cnn85_checkpoints/iter'+str(i))\n",
    "    print(\"Model \" + str(i) +\"evaluating:\")\n",
    "    model.evaluate(X_val,y_val)\n",
    "    tf.keras.backend.clear_session()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "79fa88b5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe1e5503",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b720637e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2ecfcf80",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c3432ac",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9a97a2ed",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c85fae8",
   "metadata": {},
   "outputs": [],
   "source": [
    "#attr_data_path = \"list_attr_celeba.csv\"\n",
    "#images_data_path = \"C:/Users/foreh/Documents/celeba/greyscale\"\n",
    "\n",
    "tf.keras.backend.clear_session()\n",
    "width = 178\n",
    "height = 218\n",
    "df_org = pd.read_csv(attr_data_path)\n",
    "\n",
    "df = df_org[190000:202600]\n",
    "df = df.replace(-1,0)\n",
    "#print(df.head(5))\n",
    "images_data = list()\n",
    "for idx in range(df.shape[0]):\n",
    "    path = \"{}/{}\".format(str(images_data_path),str(df.iloc[idx].image_id))\n",
    "    image = PIL.Image.open(path)\n",
    "    image_array = np.asarray(image)\n",
    "    images_data.append(image_array)\n",
    "images_data = np.array(images_data)\n",
    "def image_from_index(index, size=(width,height), path=images_data_path):\n",
    "    path = \"{}/{}\".format(str(path),str(df.iloc[index].image_id))\n",
    "    # to read the image\n",
    "    image = PIL.Image.open(path).resize(size)\n",
    "    image_array = np.asarray(image)\n",
    "\n",
    "    return image_array\n",
    "images = images_data # list of array of images\n",
    "labels = df[[\"image_id\", \"Male\"]]  # dataframe of image features\n",
    "labels=labels.drop([\"image_id\"],axis=1)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d994f13b",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "for i in range(1, 40):\n",
    "    tf.keras.backend.clear_session()\n",
    "    print(\"###### EVAL MODEL \"+str(i)+\"######\")\n",
    "    model1 = tf.keras.models.load_model('cnn85_checkpoints/iter'+str(i))\n",
    "    model1.evaluate(images,labels)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d0b5e51",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
